default.yaml
Diese Datei enthält Standardkonfigurationen für Dein Projekt.

yaml
# Default-Konfigurationen für RF Optical Futuristics-Physics x PRAI
app_name: "RF Optical Futuristics-Physics x PRAI"
version: "1.0.0"
environment: "default"

# RF-Signal-Parameter
rf_signal:
  frequency: 1000000    # Standardfrequenz (Hz)
  amplitude: 1.0        # Standardamplitude
  duration: 0.01        # Standarddauer (Sekunden)
  sampling_rate: 1000000 # Standard-Abtastrate (Hz)

# Optische Wechselwirkungsparameter
optical_simulation:
  optical_constant: 1.5 # Standard-Brechungsindex

# KI-Konfigurationen
ai_model:
  input_shape: 10       # Eingabegröße des Modells
  learning_rate: 0.001  # Standard-Lernrate

# Logging-Einstellungen
logging:
  level: "INFO"
  file: "logs/app.log"

# Ports
ports:
  chatbox: 5000         # Port für Chatbox
  api: 5001             # Port für API

Hinweise
Standardkonfiguration (default.yaml):

Wird von Deiner Anwendung verwendet, um Grundwerte festzulegen.

Kann bei Bedarf überschrieben werden, z. B. durch spezifische Werte aus der Entwicklungsumgebung.