name: Auto-Update Dependencies

on:
  schedule:
    - cron: '0 3 * * 1' # Wöchentlich um 3:00 Uhr am Montag

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update Requirements File
        run: |
          pip list --outdated --format=freeze > outdated.txt
          pip install -r outdated.txt --upgrade
          pip freeze > requirements.txt
