name: Auto-Update Dependencies

on:
  schedule:
    - cron: '0 3 * * 1' # Wöchentlich um 3:00 Uhr am Montag

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update Requirements File
        run: |
          pip list --outdated --format=freeze > outdated.txt
          pip install -r outdated.txt --upgrade
          pip freeze > requirements.txt


name: Auto Update Dependencies

on:
  schedule:
    - cron: "0 2 * * 1" # Jeden Montag um 2:00 Uhr
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Update Dependencies
        run: |
          pip install -U -r requirements.txt
          echo "Abhängigkeiten erfolgreich aktualisiert!"

      - name: Verify Updates
        run: |
          echo "Installierte Pakete nach Aktualisierung:"
          pip list
