name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # Neueste stabile Version

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Validate requirements.txt
        run: |
          echo "Validiere die requirements.txt Datei..."
          if grep -q "tensorflow==" requirements.txt; then
            echo "Requirements enthalten TensorFlow. Fortfahren..."
          else
            echo "WARNUNG: TensorFlow fehlt in requirements.txt. Prüfung erforderlich."
            exit 1
          fi

      - name: Install Dependencies
        run: |
          echo "Installiere Abhängigkeiten..."
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          echo "Führe Unit-Tests aus..."
          python -m unittest discover tests || echo "Einige Tests sind fehlgeschlagen!"

      - name: Static Analysis
        run: |
          echo "Starte statische Codeanalyse mit flake8..."
          pip install flake8
          flake8 . || echo "WARNUNG: Es wurden Coding-Probleme gefunden!"
