name: CI/CD Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Set up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test

      - name: Generate Coverage Report
        run: npm run coverage
