name: Install and Verify Dependencies

on:
  push:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Missing Dependencies
        run: |
          python sandbox/install_dependencies.py

      - name: Verify Requirements File
        run: |
          echo "Folgende Abhängigkeiten sind installiert:"
          cat requirements.txt
