name: Download Build Artifacts

on:
  workflow_dispatch:

jobs:
  download-artifacts:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-output  # Name des Artefakts, das heruntergeladen werden soll
          path: ./downloads  # Speicherort für die Artefakte
