name: Install Dependencies Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install-dependencies:
    strategy:
      matrix:
        os: [ubuntu-latest, self-hosted-linux, self-hosted-macos, self-hosted-windows]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python sandbox/install_and_validate_dependencies.py

      - name: Verify Dependencies
        run: |
          echo "Installierte Pakete:"
          pip list
