name: Libwebp Security Check

on:
  push:
    branches:
      - main

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Libwebp Version
        run: |
          echo "Überprüfen der libwebp-Version..."
          if ! dpkg -s libwebp-dev | grep -q '1.3.2'; then
            echo "Unsichere libwebp-Version entdeckt! Aktualisiere libwebp..."
            sudo apt-get update && sudo apt-get install -y libwebp-dev
          else
            echo "libwebp ist auf dem neuesten Stand!"
          fi
