name: Test and Build Across OS and Runtimes

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-build:
    name: Test on Node ${{ matrix.node_version }} and OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: ['18.x', '20.x']

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Set up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install Dependencies
        run: |
          echo "Installiere Dependencies..."
          npm install

      - name: Build Application
        run: |
          echo "Erstelle Applikation..."
          npm run build --if-present

      - name: Run Tests
        run: |
          echo "Führe Tests aus..."
          npm test

      - name: Conditional Step - Publish
        if: github.event_name == 'push'
        run: |
          echo "Veröffentliche Paket..."
          npm publish
