name: Security Tests Workflow

on:
  push:
    branches:
      - main

jobs:
  run-security-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Security Tests
        run: pytest tests/security_tests.py
