name: Security Scan Workflow

on:
  push:
    branches:
      - main

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Safety
        run: pip install safety

      - name: Run Security Scan
        run: safety check
