name: Self-Hosted Runner Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Example Command
        run: echo "Self-Hosted Runner ist aktiv und funktioniert!"
