name: Setup Go Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-go:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Setup Go Environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Installiert Go Version 1.20
