name: Setup Java JDK Environment

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  setup-java:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Installiert Java JDK Version 17
          distribution: 'temurin'  # Nutzt das Temurin JDK
