name: Validate TensorFlow and Dependencies

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-dependencies:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]  # Kompatible Versionen für TensorFlow
        os: [ubuntu-latest, macos-latest, windows-latest]  # Unterstützte Plattformen
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          # Überprüfen der Kompatibilität der requirements.txt
          if grep -q "tensorflow==" requirements.txt; then
            echo "Requirements enthalten TensorFlow. Validierung wird fortgesetzt."
          else
            echo "WARNUNG: TensorFlow fehlt in requirements.txt. Bitte prüfen."
            exit 1
          fi

          # Installation der Abhängigkeiten
          pip install -r requirements.txt

      - name: Verify TensorFlow Installation
        run: |
          # Überprüfen der TensorFlow-Installation
          python -c "import tensorflow as tf; print('TensorFlow-Version:', tf.__version__)"
          if [ $? -ne 0 ]; then
            echo "TensorFlow konnte nicht importiert werden. Bitte prüfen."
            exit 1
          fi

      - name: Display Installed Packages
        run: |
          echo "Installierte Python-Pakete:"
          pip list
