name: YAML Validator Workflow

on:
  push:
    branches:
      - main

jobs:
  validate-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate YAML Syntax
        run: |
          sudo apt-get update && sudo apt-get install -y yamllint
          yamllint .github/workflows/
